/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './index.html',
    './main.jsx',
    './App.{js,jsx}',
    './Auth.{js,jsx}',
    './screens/**/*.{js,jsx}',
    './navigation/**/*.{js,jsx}',
    './components/**/*.{js,jsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#ae7f59",
        "on-primary-fixed-variant": "#444173",
        "background": "#fcf8fd",
        "surface-dim": "#dcd9de",
        "surface-container-highest": "#e5e1e6",
        "primary-fixed": "#e3dfff",
        "surface-tint": "#5b598c",
        "on-tertiary-fixed-variant": "#633e1e",
        "surface-variant": "#e5e1e6",
        "on-error": "#ffffff",
        "on-background": "#1c1b1f",
        "on-secondary-fixed": "#2c0051",
        "on-secondary-fixed-variant": "#6900b3",
        "outline-variant": "#c8c5d0",
        "inverse-primary": "#c4c1fb",
        "surface-container": "#f1ecf2",
        "on-surface-variant": "#47464f",
        "surface": "#fcf8fd",
        "secondary-container": "#9c48ea",
        "primary-container": "#1e1b4b",
        "inverse-on-surface": "#f3eff4",
        "tertiary": "#160700",
        "error-container": "#ffdad6",
        "surface-bright": "#fcf8fd",
        "on-primary-container": "#8683ba",
        "primary": "#070235",
        "surface-container-lowest": "#ffffff",
        "secondary": "#8127cf",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#f1bc91",
        "surface-container-high": "#ebe7ec",
        "secondary-fixed-dim": "#ddb7ff",
        "tertiary-fixed": "#ffdcc2",
        "on-secondary-container": "#fffbff",
        "primary-fixed-dim": "#c4c1fb",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "tertiary-container": "#371a00",
        "secondary-fixed": "#f0dbff",
        "outline": "#787680",
        "on-tertiary-fixed": "#2e1500",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#181445",
        "surface-container-low": "#f6f2f7",
        "inverse-surface": "#313034",
        "on-surface": "#1c1b1f",
        "error": "#ba1a1a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        xxl: "48px",
        xs: "4px",
        md: "16px",
        base: "8px",
        "margin-mobile": "16px",
        "container-max": "1280px",
        xl: "32px",
        sm: "12px",
        lg: "24px",
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        "headline-sm": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-sm": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
};
